### PR TITLE
Added an example about using deps.clj script to produce the classpath

### PR DESCRIPTION
**Pull request by Rovanion**
I found the examples using aliases hard to understand and didn't want to spin up an entire clojure instance to calculate the classpath.

Feel free to do with it as you want.

### CODE REVIEW

**Comment by borkdude** [comment]
@Rovanion Isn't it much simpler to start bb like `bb -cp src:test --socket-repl 1666`?

**Comment by Rovanion** [comment]
Yup, as long as there are no external dependencies that would be simpler. But I did not understand that doing so was a possibility from reading the README. Now that I see your example here I understand it though.

Perhaps that should be a section in the readme:

If you have a larger script with a classic Clojure structure like:

```
$ tree
...
```

Then you may start a socket repl like:

```
bb -cp src:test --socket-repl 1666
```

**Comment by borkdude** [comment]
Yes, if you could change your PR to add that, that would be nice.

**Comment by Rovanion** [comment]
Modified, hope it fits the bill!

**Comment by borkdude** [comment]
Thanks!

**Pull request merged**
