### PR TITLE
Adapt net/wait-for-it as wait/wait-for-(port|path)

### PR DESCRIPTION
**Pull request by sogaiu**
Here's my initial attempt at wait/wait-for-port and wait/wait-for-path as discussed on slack a bit back.

### CODE REVIEW

**Comment by borkdude** [comment]
Great! Can you also update the README?

**Comment by sogaiu** [comment]
How does the README look now?

**Comment by borkdude** [comment]
Looks good. Can you add tests for default for both wait-for-port and wait-for-path? Also I'd like to see a test for the non-timeout case of wait-for-path if that is possible.

**Comment by sogaiu** [comment]
I can work on those things.

I'm a bit on the cautious side regarding creating and deleting files.  Is there a way within babashka to create temp files appropriately?  I saw that in one of the tests there is java.io.File/createTempFile -- but iiuc that's not exposed to babashka.

**Comment by borkdude** [comment]
@sogaiu I think `java.io.File.createTempFile()` is not implemented yet, but now might be a good time to add it:

https://github.com/borkdude/babashka/blob/master/src/babashka/impl/File.clj

Alternatively you can just create temp files in `/tmp`. Be sure to delete them first, so the file won't be there from the previous test run.

**Comment by sogaiu** [comment]
Thanks for the comments.

I'll investigate the createTempFile angle as I'm wary of messing up someone's data accidentally.

**Comment by sogaiu** [comment]
Added createTempFile with a test and hopefully improved the wait-for-path testing.

**Comment by sogaiu** [comment]
May be it would be better for createTempFile to exist as File/createTempFile since getenv is available as System/getenv.

**Pull request merged**
