### PR TITLE
adding support for clojure.zip

### PR DESCRIPTION
**Pull request by mbjarland**
also adding library support, library test, and documentation for clojure.data.zip

### CODE REVIEW

**Comment by 4mitch** [comment]
Sorry, but is this already in babashka for windows in scoop? 
I've updated upto Babashka v0.1.1 and (require '[clojure.data.zip.xml]) gives me an error :(

**Comment by borkdude** [comment]
@4mitch The `clojure.zip` namespace is part of the standard clojure library. `clojure.data.zip.xml` is something else I believe.

**Comment by borkdude** [comment]
@4mitch Oh actually, you can now use `clojure.data.zip` as a library. See:

https://github.com/borkdude/babashka/blob/master/doc/libraries.md#clojuredatazip

**Comment by 4mitch** [comment]
> @4mitch Oh actually, you can now use `clojure.data.zip` as a library. See:
> 
> https://github.com/borkdude/babashka/blob/master/doc/libraries.md#clojuredatazip

This is exactly the example I come from :) And it doesn't work with bb from scoop for me. 
I am able to require ```clojure.zip```, ```clojure.data.xml```, but not ```clojure.data.zip.xml``` from this example :(

And I thought that bb cannot require external libraries 🤔, can't it?

**Comment by borkdude** [comment]
@4mitch There are a couple of issues that I've found while trying to make it work.

For starters, for some reason I can't capture the output of `clojure` into an environment variable, but it did work with [`deps.exe`](https://github.com/borkdude/deps.clj):

```
 $env:BABASHKA_CLASSPATH=(deps.exe -Spath -Sdeps '{:deps {org.clojure/data.zip {:mvn/version \"1.0.0\"}}}') | Out-String  
```

Now the classpath is set correctly which can be verified with:

```
PS C:\Users\borkdude\Downloads> .\bb
Babashka v0.1.1-SNAPSHOT REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (System/getenv "BABASHKA_CLASSPATH")
"src;C:\\Users\\borkdude\\.m2\\repository\\org\\clojure\\clojure\\1.10.1\\clojure-1.10.1.jar;C:\\Users\\borkdude\\.m2\\repository\\org\\clojure\\data.zip\\1.0.0\\data.zip-1.0.0.jar;C:\\Users\\borkdude\\.m2\\repository\\org\\clojure\\spec.alpha\\0.2.176\\spec.alpha-0.2.176.jar;C:\\Users\\borkdude\\.m2\\repository\\org\\clojure\\core.specs.alpha\\0.2.44\\core.specs.alpha-0.2.44.jar\r\n"
```

But for some reason I still can't require `clojure.data.zip.xml`. I'll make a separate issue out of this.

**Pull request merged**
